site_name: Sistem E-Masjid.My
site_url: https://docs.e-masjid.my/
repo_url: https://github.com/Dev4w4n/e-masjid.my
repo_name: Dev4w4n/e-masjid.my
copyright: E-Masjid.my © 2023-2024
extra:
  social:
    - icon: material/text-box-search
      link: https://github.com/Dev4w4n/docs.e-masjid.my
      name: Sumber Dokumentasi
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme:
  name: material
  logo: assets/img/misc/logo.png
  favicon: assets/img/misc/favicon.ico
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
plugins:
  - glightbox
  - search